Update bash_test.yml

diff --git a/.github/workflows/bash_test.yml b/.github/workflows/bash_test.yml
--- a/.github/workflows/bash_test.yml
+++ b/.github/workflows/bash_test.yml
@@ -21,11 +21,9 @@ jobs:
           curl -XGET -s -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
           "https://api.github.com/repos/popcube/Twitter_api/actions/runs/${{ inputs.rid }}/artifacts" |\
           jq -r '.artifacts[0].id | tostring | "artifact_id=" + .' | tee log.txt >> $GITHUB_ENV
-          
-          cat log.txt
-          grep -E 'artifact_id=[0-9]+$' log.txt
+        
           grep -E 'artifact_id=[0-9]+$' log.txt ||\
-          echo "artifact id is not found. fix bug or retry later" && exit 1
+          (echo "artifact id is not found. fix bug or retry later" && exit 1)
       
       - name: download artifact
         run: |
